SELECT 
  SW, COUNT(*) as total,
  COUNT(DISTINCT CONCAT(CAST(ITEM AS STRING),'|',PAIS,'|',IFNULL(COMPETIDOR,''),'|',IFNULL(FORMATO,''),'|',CAST(IFNULL(CODIGO_ZONA,0) AS STRING))) as combos_unicas,
  COUNTIF(PRECIO_COMP_LOW IS NULL) as nulos_comp,
  COUNTIF(PRECIO_WM_LOW IS NULL) as nulos_wm
FROM `wmt-k1-cons-data-users.k1_adhoc_tables.PGMB_PREMED_A0M1J1N`
WHERE ANIO = 2026 AND SW IN (7,8)
GROUP BY SW