-- ============================================
-- TIPO: Medicion Trans
-- ============================================
SELECT
  *,
  'Medicion Trans' AS tipo_de_medicion
FROM (
WITH B3 AS(
SELECT A.* , 
  1-(SAFE_DIVIDE(PRECIO_WM,PRECIO_COMP)) AS PG_LINE
FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0g0dn3_pg_low_trans A 
),
SALIDA AS(
SELECT B3.*,CASE WHEN A.FIJACION IS NULL THEN "SIN FIJACION" ELSE A.FIJACION END AS FIJACION,
CASE WHEN A.AC IS NULL THEN "RESTO" ELSE AC END AS AC_DESC,
CASE WHEN A.FLG_AC IS NULL THEN "SIN AC" ELSE FLG_AC END AS FLG_AC,
CASE WHEN PG_LINE<-0.15 THEN "<-15%" ELSE 
CASE WHEN PG_LINE>=-0.15 AND PG_LINE<-0.12 THEN "-15% A -12%" ELSE 
CASE WHEN PG_LINE>=-0.12 AND PG_LINE<-0.09 THEN "-12% A -9%" ELSE 
CASE WHEN PG_LINE>=-0.09 AND PG_LINE<-0.06 THEN "-9% A -6%" ELSE 
CASE WHEN PG_LINE>=-0.06 AND PG_LINE<-0.03 THEN "-6% A -3%" ELSE 
CASE WHEN PG_LINE>=-0.03 AND PG_LINE<0 THEN "-3% A 0%" ELSE 
CASE WHEN PG_LINE>=0 AND PG_LINE<0.03 THEN "0% A 3%" ELSE 
CASE WHEN PG_LINE>=0.03 AND PG_LINE<0.06 THEN "3% A 6%" ELSE 
CASE WHEN PG_LINE>=0.06 AND PG_LINE<0.09 THEN "6% A 9%" ELSE 
CASE WHEN PG_LINE>=0.09 AND PG_LINE<0.12 THEN "9% A 12%" ELSE 
CASE WHEN PG_LINE>=0.12 AND PG_LINE<0.15 THEN "12% A 15%" ELSE 
CASE WHEN PG_LINE>=0.15 THEN ">15%" ELSE "REVISAR" END END END END END END END END END END END END AS RANGOS,
CASE WHEN ITEM_WM IS NULL THEN "NO" ELSE "SI" END AS CANASTA_BASICA,
CASE WHEN CATEGORIA_PERCEPCION IS NULL THEN "NO" ELSE "SI" END AS CATEGORIA_PERCEPCION,
CASE WHEN B.CADENA IS NOT NULL THEN "SI" ELSE "NO" END AS COMPETIDOR_NIELSEN,
FROM b3
LEFT JOIN wmt-k1-cons-data-users.k1_adhoc_tables.PRICING_INFO_CAM_A0M1J1N_AC A 
ON A.ITEM = B3.ITEM AND A.FORMATO = B3.FORMATO AND A.ANIO = B3.ANIO AND A.SW = B3.SW
left join wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0g0dn3_competidores_nielsen B 
ON B3.PAIS = B.PAIS AND b3.COMPETIDOR=B.CADENA 
LEFT JOIN (SELECT DISTINCT ITEM_WM FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_canasta_basica`) CB ON CB.ITEM_WM = B3.ITEM
LEFT JOIN(SELECT distinct categoria_percepcion, pais FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_categorias_percepcion` ) CP ON CP.CATEGORIA_PERCEPCION = B3.CATEGORIA AND CP.PAIS = B3.PAIS
WHERE ID_SW IN (SELECT DISTINCT ID_SW FROM B3 ORDER BY 1 DESC LIMIT 6)
),
SALIDA_2 AS (
SELECT 
DISTINCT 
A.ITEM AS ITEM_NBR, 
FLG_AC AS ACTIVIDAD_COMERCIAL, 
FLG_AC,A.ANIO,
A.CATEGORIA,
A.MP_MC,
VENDOR_NAME,
--SUBDIVISION,
CATEGORIA_PERCEPCION,
COD_CANASTO, 
COMPETIDOR, 
CODIGO_ZONA AS COD_ZONA,
DEPTO AS DEP_NBR, 
ITEM_DESCRIP ASDESCRIPCION,
A.DIVISION,
FIJACION ASFIJACIONES,
KVI_NBB,
MES,
OPPAS FLAG_OPP,
PAIS,
ROL_CANASTO AS ROLL_CANASTO,
A.ID_SW,
A.SW AS SEMANA, 
UPC , 
ZONA,
CANASTA_BASICA AS FLAG_CANASTA_BASICA,
FLAG_CHPR_COMP ASFLAG_COMP_MB, 
PRECIO_COMP AS PRECIO_COMP_PONDERADO , 
PRECIO_WM ASPRECIO_WM_PONDERADO,
PESO AS PESO_CAM,
FACTOR AS FACTOR,
PESO_CALC AS PESO_MB,
FACTOR_CALC AS FACTOR_MB,
MB,
PARTICIPA AS PARTICIPA_MB,
MB_CALC AS MB_MB_CALC,
PARTICIPA_CALC AS PARTICIPA_MB_CALC,
PG_LINE ASPRICE_GAP,
RANGOS ASRANGO_PG,
DIVISION_COMERCIAL,
COMPETIDOR_NIELSEN,
AC_DESC AS TIPO_AC,
FORMATO,
SUBDIVISION,
brand_name as Marca,
COMP_RCCN AS COMPE_REACCION,
CONCAT(FLANKER,"-",CARRITO) AS FLAG_FC,
FACTOR_META_BASE AS FACTOR_META,
PESO_META_BASE AS PESO_META,
CASE WHEN FLAG IS NULL THEN "ELIMINADO" ELSE FLAG END AS FLAG_CANASTO_NUEVO,
CASE WHEN E.CATEGORIA IS NULL THEN "NO" ELSE "SI" END AS ENFOQUE
 FROM SALIDA A
LEFT JOIN(SELECT DISTINCT ITEM_NBR, COMP_NM, zone_cd, CAST(ID AS INT64) AS ID_SW, reaction_comp_nm AS COMP_RCCN, item_subdiv AS SUBDIVISION, YR_NBR,WM_WK_NBR,prcsmrt_bskt_flg AS PS
FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0g0dn3_price_gap_trns
LEFT JOIN `wmt-k1-cons-data-users.k1_adhoc_tables.DIAS_WM_INDEX` AS INDICE 
ON CONCAT(INDICE.ANIO,INDICE.WM_WK) = CONCAT(YR_NBR,WM_WK_NBR)
WHERE role_att IN ("MEDICION")
AND price_type="CORPORATIVO"
and wfm_flg in ("False","NO") 
AND YR_NBR in(2026,2025)) B ON A.ITEM = B.ITEM_NBR AND A.COMPETIDOR=B.COMP_NM AND A.CODIGO_ZONA = B.ZONE_CD AND A.ID_SW=B.ID_SW 
LEFT JOIN (SELECT DISTINCT ITEM_NBR, CARRITO, FLANKER,SW,ANIO FROM wmt-k1-cons-data-users.k1_adhoc_tables.items_fc_hstrc_a0m1j1n) 
FC ON A.ITEM = FC.ITEM_NBR AND A.ANIO = FC.ANIO AND A.SW = FC.SW 
LEFT JOIN(SELECT distinct ITEM,flag FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0g0dn3_canasto_universal_extendido`  ) CU ON CU.ITEM = A.ITEM
LEFT JOIN(SELECT DISTINCT CATEGORIA FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0m1j1n_categorias_enfoque` WHERE ENFOQUE = "SI") E ON E.CATEGORIA = A.CATEGORIA),
PERFORMANCE_BQ AS (WITH
PASO_1 AS (
SELECT
DISTINCT 
T1.COD_ZONA AS cod_zona,
T1.FORMATO,
T1.PAIS,
T1.ITEM_NBR AS cod_item,
SAFE_DIVIDE(FACTOR_MB_TW,PESO_MB_TW) AS PG_TW,
SAFE_DIVIDE(FACTOR_MB_LW,PESO_MB_LW) AS PG_LW,
SAFE_DIVIDE(FACTOR_MB_2LW,PESO_MB_2LW) AS PG_2LW,
SAFE_DIVIDE(FACTOR_MB_3LW,PESO_MB_3LW) AS PG_3LW,
SAFE_DIVIDE(FACTOR_MB_4LW,PESO_MB_4LW) AS PG_4LW,
SAFE_DIVIDE(FACTOR_MB_5LW,PESO_MB_5LW) AS PG_5LW,
SAFE_DIVIDE(FACTOR_META_TW,PESO_META_TW) AS META_TW,
SAFE_DIVIDE(FACTOR_META_LW,PESO_META_LW) AS META_LW,
SAFE_DIVIDE(FACTOR_META_2LW,PESO_META_2LW) AS META_2LW,
SAFE_DIVIDE(FACTOR_META_3LW,PESO_META_3LW) AS META_3LW,
SAFE_DIVIDE(FACTOR_META_4LW,PESO_META_4LW) AS META_4LW,
SAFE_DIVIDE(FACTOR_META_5LW,PESO_META_5LW) AS META_5LW,
FROM  SALIDA_2 T1
LEFT JOIN (
 --- TW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_TW,
SUM(FACTOR_MB) FACTOR_MB_TW,
SUM(FACTOR_META) AS FACTOR_META_TW,
SUM(PESO_META) AS PESO_META_TW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW) FROM SALIDA_2 )
 GROUP BY 1,2) T2 ON T1.ITEM_NBR=T2.ITEM_NBR AND T1.COD_ZONA=T2.COD_ZONA
 LEFT JOIN 
 (
   --- LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_LW,
SUM(FACTOR_MB) FACTOR_MB_LW,
SUM(FACTOR_META) AS FACTOR_META_LW,
SUM(PESO_META) AS PESO_META_LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-1 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T3 ON T1.ITEM_NBR=T3.ITEM_NBR AND T1.COD_ZONA=T3.COD_ZONA
  LEFT JOIN 
 (
     --- 2LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_2LW,
SUM(FACTOR_MB) FACTOR_MB_2LW,
SUM(FACTOR_META) AS FACTOR_META_2LW,
SUM(PESO_META) AS PESO_META_2LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-2 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T4 ON T1.ITEM_NBR=T4.ITEM_NBR AND T1.COD_ZONA=T4.COD_ZONA
  LEFT JOIN 
 (
       --- 3LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_3LW,
SUM(FACTOR_MB) FACTOR_MB_3LW,
SUM(FACTOR_META) AS FACTOR_META_3LW,
SUM(PESO_META) AS PESO_META_3LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-3 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T5 ON T1.ITEM_NBR=T5.ITEM_NBR AND T1.COD_ZONA=T5.COD_ZONA
 LEFT JOIN 
 (
--4- LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_4LW,
SUM(FACTOR_MB) FACTOR_MB_4LW,
SUM(FACTOR_META) AS FACTOR_META_4LW,
SUM(PESO_META) AS PESO_META_4LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-4 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T6 ON T1.ITEM_NBR=T6.ITEM_NBR AND T1.COD_ZONA=T6.COD_ZONA
  LEFT JOIN 
  (
--5 LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_5LW,
SUM(FACTOR_MB) FACTOR_MB_5LW,
SUM(FACTOR_META) AS FACTOR_META_5LW,
SUM(PESO_META) AS PESO_META_5LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-5 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T7 ON T1.ITEM_NBR=T7.ITEM_NBR AND T1.COD_ZONA=T7.COD_ZONA
 ),
 PASO_2 AS (
 SELECT *, CASE  WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=6  THEN 6
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=5  THEN 5
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=4  THEN 4
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=3  THEN 3
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=2  THEN 2
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=1  THEN 1
ELSE NULL
END SEMANAS_NEG,
CASE  WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=6  THEN 6
 WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=5  THEN 5
 WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=4  THEN 4
WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=3  THEN 3
WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=2  THEN 2
WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=1  THEN 1
ELSE NULL
END SEMANAS_SOBREMETA,
CASE
  WHEN (PG_TW < 0 AND PG_LW < 0 AND PG_2LW < 0 AND PG_3LW < 0) THEN "NEG 4 WKS"
      WHEN (PG_TW < 0 AND PG_LW < 0 AND PG_2LW < 0) THEN "NEG 3 WKS"
       WHEN (PG_TW < 0 AND PG_LW < 0 ) THEN "NEG 2 WKS"
        WHEN (PG_TW < 0  ) THEN "NEG 1 WKS"
        WHEN (PG_TW IS NULL AND PG_LW IS NULL ) THEN "ULTIMAS 2 WKS SIN PG"
        WHEN (PG_TW > META_TW*1.05) AND (PG_LW> META_LW*1.05) AND (PG_2LW> META_2LW*1.05) AND (PG_3LW> META_3LW*1.05) THEN "EXCEDIDO 4 WKS"
        WHEN (PG_TW > META_TW*1.05) AND (PG_LW> META_LW*1.05) AND (PG_2LW> META_2LW*1.05)  THEN "EXCEDIDO 3 WKS"
        WHEN (PG_TW > META_TW*1.05) AND (PG_LW> META_LW*1.05)   THEN "EXCEDIDO 2 WKS"
       WHEN (PG_TW > META_TW*1.05)  THEN "EXCEDIDO 1 WKS"
       ELSE NULL
    END PERFORMANCE,
COUNT(*) OVER (PARTITION BY cod_item) AS CONTEO,
SUM(CASE WHEN (PG_TW < 0 AND PG_LW < 0 AND PG_2LW < 0 AND PG_3LW < 0)  THEN 1 ELSE 0 END) OVER(PARTITION BY cod_item) AS CONTEO_NEGATIVO
  FROM PASO_1),
FINAL AS (
SELECT * EXCEPT(FIJACION,DETALLE_FIJACION,FIJACION_2), 
CASE WHEN DETALLE_FIJACION IS NOT NULL AND FIJACION_2 IS NOT NULL THEN CONCAT(DETALLE_FIJACION,"/",FIJACION_2) WHEN DETALLE_FIJACION IS NOT NULL THEN DETALLE_FIJACION ELSE FIJACION_2
 END AS DETALLE_FIJACION
 FROM (
  SELECT A.*,safe_divide(conteo_negativo,conteo) as porc_negativos_zonas,
  case when b.DETALLE_FIJACION like "%MOM%" THEN B.DETALLE_FIJACION WHEN B.DETALLE_FIJACION IS NOT NULL AND C.FIJACION IS NOT NULL THEN CONCAT(DETALLE_FIJACION,"/",C.FIJACION)
  WHEN DETALLE_FIJACION IS NOT NULL AND C.FIJACION IS NULL THEN DETALLE_FIJACION ELSE C.FIJACION END AS DETALLE_FIJACION,
  CASE WHEN D.FIJACION IS NOT NULL AND R.FIJACION IS NOT NULL THEN CONCAT(D.FIJACION,"/",R.FIJACION) WHEN D.FIJACION IS NOT NULL THEN D.FIJACION ELSE R.FIJACION END AS FIJACION_2, 
  R.FIJACION,c.fijacion as fijacion_mom,d.FIJACION as fijacion_max,r.FIJACION as fijacion_comercial
  FROM PASO_2 A
  LEFT jOIN (SELECT ITEM,COD_ZONA,FIJACION AS DETALLE_FIJACION,CASE WHEN FIJACION LIKE "%MD%" OR FIJACION LIKE "%RB%" OR FIJACION LIKE "%GP%" OR FIJACION LIKE "%AT%" OR FIJACION LIKE "%EV_4K%" THEN "Y" ELSE "X" END AS FIJACION
  FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_historico_insumos WHERE EXTRACT_DATE=(SELECT MAX(EXTRACT_DATE) FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_historico_insumos )AND FIJACION IS NOT NULL) B
  ON A.COD_ITEM=B.ITEM AND A.COD_ZONA=B.COD_ZONA
left join (SELECT * FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_fijaciones_estrategia` WHERE FIJACION LIKE"%MOM%") c on a.cod_item=c.item and a.cod_zona=c.cod_zona
  left join (SELECT * FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_fijaciones_estrategia` WHERE FIJACION LIKE"%MAX%") d on a.cod_item=D.item and a.cod_zona=d.cod_zona
  left join (SELECT DISTINCT ITEM_NBR,COD_ZONA,"FIJACION COMERCIAL" AS FIJACION FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_fijacion_comercial`) R on a.cod_item=R.ITEM_NBR and a.cod_zona=R.cod_zona))
  SELECT *, CASE WHEN DETALLE_FIJACION LIKE "%MD%" OR DETALLE_FIJACION LIKE "%RB%" OR DETALLE_FIJACION LIKE "%GP%" OR DETALLE_FIJACION LIKE "%AT%" OR DETALLE_FIJACION LIKE "%EV_4K%" 
  OR DETALLE_FIJACION LIKE "%FIJACION COMERCIAL%"
  THEN "Y" WHEN DETALLE_FIJACION LIKE "%MOM%" OR DETALLE_FIJACION LIKE "%MAX%" THEN "X"  ELSE NULL END AS FIJACION, CASE WHEN DETALLE_FIJACION IS NOT NULL THEN "FIJADO" ELSE "NO FIJADO"
   END AS FLAG_FIJADO,fijacion_mom
   FROM FINAL
)
SELECT A.*,SEMANAS_NEG,SEMANAS_SOBREMETA,PERFORMANCE,CASE WHEN porc_negativos_zonas >=0.9 THEN "90% ZONAS NEG 4WK" WHEN porc_negativos_zonas >=0.5 THEN "50% ZONAS NEG 4WK"  ELSE NULL END AS ZONAS_NEGATIVO,DETALLE_FIJACION,FIJACION,FLAG_FIJADO,SEMANAS_NEGATIVAS_CONSECUTIVAS, SEMANAS_SOBRE_META_CONSECUTIVAS, 
CASE WHEN CLASIFICACION_ACTUAL IS NULL THEN KVI_NBB ELSE CLASIFICACION_ACTUAL END AS CLASIFICACION_ACTUAL,CLASIFICACION_ANTERIOR,FLAG_CANASTO_ANTERIOR,CASE WHEN FLAG_CANASTO_ACTUAL IS NULL THEN "CANASTO ACTUAL" ELSE FLAG_CANASTO_ACTUAL END AS FLAG_CANASTO_ACTUAL, 
CASE WHEN FLAG_CANASTO_ANTERIOR = "CANASTO ANTERIOR" AND FLAG_CANASTO_ACTUAL = "CANASTO ACTUAL" THEN "MANTIENE" WHEN FLAG_CANASTO_ANTERIOR = "CANASTO ANTERIOR" AND FLAG_CANASTO_ACTUAL = "NO CANASTO ACTUAL" THEN "SALE"WHEN FLAG_CANASTO_ANTERIOR = "NO CANASTO ANTERIOR" AND FLAG_CANASTO_ACTUAL = "CANASTO ACTUAL" THEN "ENTRA" ELSE "MANTIENE" END AS DETALLES_CANASTO
FROM SALIDA_2 A 
LEFT JOIN (select cod_item,cod_zona,min(semanas_neg) as semanas_neg,min(SEMANAS_SOBREMETA) as SEMANAS_SOBREMETA, min(PERFORMANCE) as PERFORMANCE, min(porc_negativos_zonas) as porc_negativos_zonas, min(detalle_fijacion) as detalle_fijacion, min(fijacion) as fijacion, min(flag_fijado) as flag_fijado from PERFORMANCE_BQ group by all) B ON A.ITEM_NBR=B.COD_ITEM AND A.COD_ZONA=B.COD_ZONA
LEFT JOIN(SELECT DISTINCT ITEM,CODIGO_ZONA,MAX(SEMANAS_NEGATIVAS_CONSECUTIVAS) SEMANAS_NEGATIVAS_CONSECUTIVAS, MAX(SEMANAS_SOBRE_META_CONSECUTIVAS)SEMANAS_SOBRE_META_CONSECUTIVAS  FROM `wmt-k1-cons-data-users.k1_adhoc_tables.performance_consecutivo`  GROUP BY 1,2) C ON C.ITEM = A.ITEM_NBR AND C.CODIGO_ZONA = A.COD_ZONA  
LEFT JOIN (SELECT ITEM,FORMATO,CLASIFICACION_ACTUAL,CLASIFICACION_ANTERIOR,FLAG_CANASTO_ACTUAL,FLAG_CANASTO_ANTERIOR FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0m1j1n_canasto_tw_vs_lw) D ON D.ITEM = A.ITEM_NBR AND D.FORMATO = A.FORMATO
)

UNION ALL

-- ============================================
-- TIPO: Medicion ROT
-- ============================================
SELECT
  *,
  'Medicion ROT' AS tipo_de_medicion
FROM (
WITH B3 AS(
SELECT A.* , 
  1-(SAFE_DIVIDE(PRECIO_WM,PRECIO_COMP)) AS PG_LINE
FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0g0dn3_pg_low_rot A 
),
SALIDA AS(
SELECT B3.*,CASE WHEN A.FIJACION IS NULL THEN "SIN FIJACION" ELSE A.FIJACION END AS FIJACION,
CASE WHEN A.AC IS NULL THEN "RESTO" ELSE AC END AS AC_DESC,
CASE WHEN A.FLG_AC IS NULL THEN "SIN AC" ELSE FLG_AC END AS FLG_AC,
CASE WHEN PG_LINE<-0.15 THEN "<-15%" ELSE 
CASE WHEN PG_LINE>=-0.15 AND PG_LINE<-0.12 THEN "-15% A -12%" ELSE 
CASE WHEN PG_LINE>=-0.12 AND PG_LINE<-0.09 THEN "-12% A -9%" ELSE 
CASE WHEN PG_LINE>=-0.09 AND PG_LINE<-0.06 THEN "-9% A -6%" ELSE 
CASE WHEN PG_LINE>=-0.06 AND PG_LINE<-0.03 THEN "-6% A -3%" ELSE 
CASE WHEN PG_LINE>=-0.03 AND PG_LINE<0 THEN "-3% A 0%" ELSE 
CASE WHEN PG_LINE>=0 AND PG_LINE<0.03 THEN "0% A 3%" ELSE 
CASE WHEN PG_LINE>=0.03 AND PG_LINE<0.06 THEN "3% A 6%" ELSE 
CASE WHEN PG_LINE>=0.06 AND PG_LINE<0.09 THEN "6% A 9%" ELSE 
CASE WHEN PG_LINE>=0.09 AND PG_LINE<0.12 THEN "9% A 12%" ELSE 
CASE WHEN PG_LINE>=0.12 AND PG_LINE<0.15 THEN "12% A 15%" ELSE 
CASE WHEN PG_LINE>=0.15 THEN ">15%" ELSE "REVISAR" END END END END END END END END END END END END AS RANGOS,
CASE WHEN ITEM_WM IS NULL THEN "NO" ELSE "SI" END AS CANASTA_BASICA,
CASE WHEN CATEGORIA_PERCEPCION IS NULL THEN "NO" ELSE "SI" END AS CATEGORIA_PERCEPCION,
CASE WHEN B.CADENA IS NOT NULL THEN "SI" ELSE "NO" END AS COMPETIDOR_NIELSEN,
FROM b3
LEFT JOIN wmt-k1-cons-data-users.k1_adhoc_tables.PRICING_INFO_CAM_A0M1J1N_AC A 
ON A.ITEM = B3.ITEM AND A.FORMATO = B3.FORMATO AND A.ANIO = B3.ANIO AND A.SW = B3.SW
left join wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0g0dn3_competidores_nielsen B 
ON B3.PAIS = B.PAIS AND b3.COMPETIDOR=B.CADENA 
LEFT JOIN (SELECT DISTINCT ITEM_WM FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_canasta_basica`) CB ON CB.ITEM_WM = B3.ITEM
LEFT JOIN(SELECT distinct categoria_percepcion, pais FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_categorias_percepcion` ) CP ON CP.CATEGORIA_PERCEPCION = B3.CATEGORIA AND CP.PAIS = B3.PAIS
WHERE ID_SW IN (SELECT DISTINCT ID_SW FROM B3 ORDER BY 1 DESC LIMIT 6)
),
SALIDA_2 AS (
SELECT 
DISTINCT 
A.ITEM AS ITEM_NBR, 
FLG_AC AS ACTIVIDAD_COMERCIAL, 
FLG_AC,A.ANIO,
A.CATEGORIA,
A.MP_MC,
VENDOR_NAME,
--SUBDIVISION,
CATEGORIA_PERCEPCION,
COD_CANASTO, 
COMPETIDOR, 
CODIGO_ZONA AS COD_ZONA,
DEPTO AS DEP_NBR, 
ITEM_DESCRIP ASDESCRIPCION,
A.DIVISION,
FIJACION ASFIJACIONES,
KVI_NBB,
MES,
OPPAS FLAG_OPP,
PAIS,
ROL_CANASTO AS ROLL_CANASTO,
A.ID_SW,
A.SW AS SEMANA, 
UPC , 
ZONA,
CANASTA_BASICA AS FLAG_CANASTA_BASICA,
FLAG_CHPR_COMP ASFLAG_COMP_MB, 
PRECIO_COMP AS PRECIO_COMP_PONDERADO , 
PRECIO_WM ASPRECIO_WM_PONDERADO,
PESO AS PESO_CAM,
FACTOR AS FACTOR,
PESO_CALC AS PESO_MB,
FACTOR_CALC AS FACTOR_MB,
MB,
PARTICIPA AS PARTICIPA_MB,
MB_CALC AS MB_MB_CALC,
PARTICIPA_CALC AS PARTICIPA_MB_CALC,
PG_LINE ASPRICE_GAP,
RANGOS ASRANGO_PG,
DIVISION_COMERCIAL,
COMPETIDOR_NIELSEN,
AC_DESC AS TIPO_AC,
FORMATO,
SUBDIVISION,
brand_name as Marca,
COMP_RCCN AS COMPE_REACCION,
CONCAT(FLANKER,"-",CARRITO) AS FLAG_FC,
FACTOR_META_BASE AS FACTOR_META,
PESO_META_BASE AS PESO_META,
CASE WHEN FLAG IS NULL THEN "ELIMINADO" ELSE FLAG END AS FLAG_CANASTO_NUEVO,
CASE WHEN E.CATEGORIA IS NULL THEN "NO" ELSE "SI" END AS ENFOQUE
 FROM SALIDA A
LEFT JOIN(SELECT DISTINCT ITEM_NBR, COMP_NM, zone_cd, CAST(ID AS INT64) AS ID_SW, reaction_comp_nm AS COMP_RCCN, item_subdiv AS SUBDIVISION, YR_NBR,WM_WK_NBR,prcsmrt_bskt_flg AS PS
FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0g0dn3_price_gap_qty
LEFT JOIN `wmt-k1-cons-data-users.k1_adhoc_tables.DIAS_WM_INDEX` AS INDICE 
ON CONCAT(INDICE.ANIO,INDICE.WM_WK) = CONCAT(YR_NBR,WM_WK_NBR)
WHERE role_att IN ("MEDICION")
AND price_type="CORPORATIVO"
and wfm_flg in ("False","NO") 
AND YR_NBR in(2026,2025)) B ON A.ITEM = B.ITEM_NBR AND A.COMPETIDOR=B.COMP_NM AND A.CODIGO_ZONA = B.ZONE_CD AND A.ID_SW=B.ID_SW 
LEFT JOIN (SELECT DISTINCT ITEM_NBR, CARRITO, FLANKER,SW,ANIO FROM wmt-k1-cons-data-users.k1_adhoc_tables.items_fc_hstrc_a0m1j1n) 
FC ON A.ITEM = FC.ITEM_NBR AND A.ANIO = FC.ANIO AND A.SW = FC.SW 
LEFT JOIN(SELECT distinct ITEM,flag FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0g0dn3_canasto_universal_extendido`  ) CU ON CU.ITEM = A.ITEM
LEFT JOIN(SELECT DISTINCT CATEGORIA FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0m1j1n_categorias_enfoque` WHERE ENFOQUE = "SI") E ON E.CATEGORIA = A.CATEGORIA),
PERFORMANCE_BQ AS (WITH
PASO_1 AS (
SELECT
DISTINCT 
T1.COD_ZONA AS cod_zona,
T1.FORMATO,
T1.PAIS,
T1.ITEM_NBR AS cod_item,
SAFE_DIVIDE(FACTOR_MB_TW,PESO_MB_TW) AS PG_TW,
SAFE_DIVIDE(FACTOR_MB_LW,PESO_MB_LW) AS PG_LW,
SAFE_DIVIDE(FACTOR_MB_2LW,PESO_MB_2LW) AS PG_2LW,
SAFE_DIVIDE(FACTOR_MB_3LW,PESO_MB_3LW) AS PG_3LW,
SAFE_DIVIDE(FACTOR_MB_4LW,PESO_MB_4LW) AS PG_4LW,
SAFE_DIVIDE(FACTOR_MB_5LW,PESO_MB_5LW) AS PG_5LW,
SAFE_DIVIDE(FACTOR_META_TW,PESO_META_TW) AS META_TW,
SAFE_DIVIDE(FACTOR_META_LW,PESO_META_LW) AS META_LW,
SAFE_DIVIDE(FACTOR_META_2LW,PESO_META_2LW) AS META_2LW,
SAFE_DIVIDE(FACTOR_META_3LW,PESO_META_3LW) AS META_3LW,
SAFE_DIVIDE(FACTOR_META_4LW,PESO_META_4LW) AS META_4LW,
SAFE_DIVIDE(FACTOR_META_5LW,PESO_META_5LW) AS META_5LW,
FROM  SALIDA_2 T1
LEFT JOIN (
 --- TW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_TW,
SUM(FACTOR_MB) FACTOR_MB_TW,
SUM(FACTOR_META) AS FACTOR_META_TW,
SUM(PESO_META) AS PESO_META_TW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW) FROM SALIDA_2 )
 GROUP BY 1,2) T2 ON T1.ITEM_NBR=T2.ITEM_NBR AND T1.COD_ZONA=T2.COD_ZONA
 LEFT JOIN 
 (
   --- LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_LW,
SUM(FACTOR_MB) FACTOR_MB_LW,
SUM(FACTOR_META) AS FACTOR_META_LW,
SUM(PESO_META) AS PESO_META_LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-1 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T3 ON T1.ITEM_NBR=T3.ITEM_NBR AND T1.COD_ZONA=T3.COD_ZONA
  LEFT JOIN 
 (
     --- 2LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_2LW,
SUM(FACTOR_MB) FACTOR_MB_2LW,
SUM(FACTOR_META) AS FACTOR_META_2LW,
SUM(PESO_META) AS PESO_META_2LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-2 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T4 ON T1.ITEM_NBR=T4.ITEM_NBR AND T1.COD_ZONA=T4.COD_ZONA
  LEFT JOIN 
 (
       --- 3LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_3LW,
SUM(FACTOR_MB) FACTOR_MB_3LW,
SUM(FACTOR_META) AS FACTOR_META_3LW,
SUM(PESO_META) AS PESO_META_3LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-3 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T5 ON T1.ITEM_NBR=T5.ITEM_NBR AND T1.COD_ZONA=T5.COD_ZONA
 LEFT JOIN 
 (
--4- LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_4LW,
SUM(FACTOR_MB) FACTOR_MB_4LW,
SUM(FACTOR_META) AS FACTOR_META_4LW,
SUM(PESO_META) AS PESO_META_4LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-4 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T6 ON T1.ITEM_NBR=T6.ITEM_NBR AND T1.COD_ZONA=T6.COD_ZONA
  LEFT JOIN 
  (
--5 LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_5LW,
SUM(FACTOR_MB) FACTOR_MB_5LW,
SUM(FACTOR_META) AS FACTOR_META_5LW,
SUM(PESO_META) AS PESO_META_5LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-5 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T7 ON T1.ITEM_NBR=T7.ITEM_NBR AND T1.COD_ZONA=T7.COD_ZONA
 ),
 PASO_2 AS (
 SELECT *, CASE  WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=6  THEN 6
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=5  THEN 5
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=4  THEN 4
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=3  THEN 3
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=2  THEN 2
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=1  THEN 1
ELSE NULL
END SEMANAS_NEG,
CASE  WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=6  THEN 6
 WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=5  THEN 5
 WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=4  THEN 4
WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=3  THEN 3
WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=2  THEN 2
WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=1  THEN 1
ELSE NULL
END SEMANAS_SOBREMETA,
CASE
  WHEN (PG_TW < 0 AND PG_LW < 0 AND PG_2LW < 0 AND PG_3LW < 0) THEN "NEG 4 WKS"
      WHEN (PG_TW < 0 AND PG_LW < 0 AND PG_2LW < 0) THEN "NEG 3 WKS"
       WHEN (PG_TW < 0 AND PG_LW < 0 ) THEN "NEG 2 WKS"
        WHEN (PG_TW < 0  ) THEN "NEG 1 WKS"
        WHEN (PG_TW IS NULL AND PG_LW IS NULL ) THEN "ULTIMAS 2 WKS SIN PG"
        WHEN (PG_TW > META_TW*1.05) AND (PG_LW> META_LW*1.05) AND (PG_2LW> META_2LW*1.05) AND (PG_3LW> META_3LW*1.05) THEN "EXCEDIDO 4 WKS"
        WHEN (PG_TW > META_TW*1.05) AND (PG_LW> META_LW*1.05) AND (PG_2LW> META_2LW*1.05)  THEN "EXCEDIDO 3 WKS"
        WHEN (PG_TW > META_TW*1.05) AND (PG_LW> META_LW*1.05)   THEN "EXCEDIDO 2 WKS"
       WHEN (PG_TW > META_TW*1.05)  THEN "EXCEDIDO 1 WKS"
       ELSE NULL
    END PERFORMANCE,
COUNT(*) OVER (PARTITION BY cod_item) AS CONTEO,
SUM(CASE WHEN (PG_TW < 0 AND PG_LW < 0 AND PG_2LW < 0 AND PG_3LW < 0)  THEN 1 ELSE 0 END) OVER(PARTITION BY cod_item) AS CONTEO_NEGATIVO
  FROM PASO_1),
FINAL AS (
SELECT * EXCEPT(FIJACION,DETALLE_FIJACION,FIJACION_2), 
CASE WHEN DETALLE_FIJACION IS NOT NULL AND FIJACION_2 IS NOT NULL THEN CONCAT(DETALLE_FIJACION,"/",FIJACION_2) WHEN DETALLE_FIJACION IS NOT NULL THEN DETALLE_FIJACION ELSE FIJACION_2
 END AS DETALLE_FIJACION
 FROM (
  SELECT A.*,safe_divide(conteo_negativo,conteo) as porc_negativos_zonas,
  case when b.DETALLE_FIJACION like "%MOM%" THEN B.DETALLE_FIJACION WHEN B.DETALLE_FIJACION IS NOT NULL AND C.FIJACION IS NOT NULL THEN CONCAT(DETALLE_FIJACION,"/",C.FIJACION)
  WHEN DETALLE_FIJACION IS NOT NULL AND C.FIJACION IS NULL THEN DETALLE_FIJACION ELSE C.FIJACION END AS DETALLE_FIJACION,
  CASE WHEN D.FIJACION IS NOT NULL AND R.FIJACION IS NOT NULL THEN CONCAT(D.FIJACION,"/",R.FIJACION) WHEN D.FIJACION IS NOT NULL THEN D.FIJACION ELSE R.FIJACION END AS FIJACION_2, 
  R.FIJACION,c.fijacion as fijacion_mom,d.FIJACION as fijacion_max,r.FIJACION as fijacion_comercial
  FROM PASO_2 A
  LEFT jOIN (SELECT ITEM,COD_ZONA,FIJACION AS DETALLE_FIJACION,CASE WHEN FIJACION LIKE "%MD%" OR FIJACION LIKE "%RB%" OR FIJACION LIKE "%GP%" OR FIJACION LIKE "%AT%" OR FIJACION LIKE "%EV_4K%" THEN "Y" ELSE "X" END AS FIJACION
  FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_historico_insumos WHERE EXTRACT_DATE=(SELECT MAX(EXTRACT_DATE) FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_historico_insumos )AND FIJACION IS NOT NULL) B
  ON A.COD_ITEM=B.ITEM AND A.COD_ZONA=B.COD_ZONA
left join (SELECT * FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_fijaciones_estrategia` WHERE FIJACION LIKE"%MOM%") c on a.cod_item=c.item and a.cod_zona=c.cod_zona
  left join (SELECT * FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_fijaciones_estrategia` WHERE FIJACION LIKE"%MAX%") d on a.cod_item=D.item and a.cod_zona=d.cod_zona
  left join (SELECT DISTINCT ITEM_NBR,COD_ZONA,"FIJACION COMERCIAL" AS FIJACION FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_fijacion_comercial`) R on a.cod_item=R.ITEM_NBR and a.cod_zona=R.cod_zona))
  SELECT *, CASE WHEN DETALLE_FIJACION LIKE "%MD%" OR DETALLE_FIJACION LIKE "%RB%" OR DETALLE_FIJACION LIKE "%GP%" OR DETALLE_FIJACION LIKE "%AT%" OR DETALLE_FIJACION LIKE "%EV_4K%" 
  OR DETALLE_FIJACION LIKE "%FIJACION COMERCIAL%"
  THEN "Y" WHEN DETALLE_FIJACION LIKE "%MOM%" OR DETALLE_FIJACION LIKE "%MAX%" THEN "X"  ELSE NULL END AS FIJACION, CASE WHEN DETALLE_FIJACION IS NOT NULL THEN "FIJADO" ELSE "NO FIJADO"
   END AS FLAG_FIJADO,fijacion_mom
   FROM FINAL
)
SELECT A.*,SEMANAS_NEG,SEMANAS_SOBREMETA,PERFORMANCE,CASE WHEN porc_negativos_zonas >=0.9 THEN "90% ZONAS NEG 4WK" WHEN porc_negativos_zonas >=0.5 THEN "50% ZONAS NEG 4WK"  ELSE NULL END AS ZONAS_NEGATIVO,DETALLE_FIJACION,FIJACION,FLAG_FIJADO,SEMANAS_NEGATIVAS_CONSECUTIVAS, SEMANAS_SOBRE_META_CONSECUTIVAS, 
CASE WHEN CLASIFICACION_ACTUAL IS NULL THEN KVI_NBB ELSE CLASIFICACION_ACTUAL END AS CLASIFICACION_ACTUAL,CLASIFICACION_ANTERIOR,FLAG_CANASTO_ANTERIOR,CASE WHEN FLAG_CANASTO_ACTUAL IS NULL THEN "CANASTO ACTUAL" ELSE FLAG_CANASTO_ACTUAL END AS FLAG_CANASTO_ACTUAL, 
CASE WHEN FLAG_CANASTO_ANTERIOR = "CANASTO ANTERIOR" AND FLAG_CANASTO_ACTUAL = "CANASTO ACTUAL" THEN "MANTIENE" WHEN FLAG_CANASTO_ANTERIOR = "CANASTO ANTERIOR" AND FLAG_CANASTO_ACTUAL = "NO CANASTO ACTUAL" THEN "SALE"WHEN FLAG_CANASTO_ANTERIOR = "NO CANASTO ANTERIOR" AND FLAG_CANASTO_ACTUAL = "CANASTO ACTUAL" THEN "ENTRA" ELSE "MANTIENE" END AS DETALLES_CANASTO
FROM SALIDA_2 A 
LEFT JOIN (select cod_item,cod_zona,min(semanas_neg) as semanas_neg,min(SEMANAS_SOBREMETA) as SEMANAS_SOBREMETA, min(PERFORMANCE) as PERFORMANCE, min(porc_negativos_zonas) as porc_negativos_zonas, min(detalle_fijacion) as detalle_fijacion, min(fijacion) as fijacion, min(flag_fijado) as flag_fijado from PERFORMANCE_BQ group by all) B ON A.ITEM_NBR=B.COD_ITEM AND A.COD_ZONA=B.COD_ZONA
LEFT JOIN(SELECT DISTINCT ITEM,CODIGO_ZONA,MAX(SEMANAS_NEGATIVAS_CONSECUTIVAS) SEMANAS_NEGATIVAS_CONSECUTIVAS, MAX(SEMANAS_SOBRE_META_CONSECUTIVAS)SEMANAS_SOBRE_META_CONSECUTIVAS  FROM `wmt-k1-cons-data-users.k1_adhoc_tables.performance_consecutivo`  GROUP BY 1,2) C ON C.ITEM = A.ITEM_NBR AND C.CODIGO_ZONA = A.COD_ZONA  
LEFT JOIN (SELECT ITEM,FORMATO,CLASIFICACION_ACTUAL,CLASIFICACION_ANTERIOR,FLAG_CANASTO_ACTUAL,FLAG_CANASTO_ANTERIOR FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0m1j1n_canasto_tw_vs_lw) D ON D.ITEM = A.ITEM_NBR AND D.FORMATO = A.FORMATO
)

UNION ALL

-- ============================================
-- TIPO: Medicion LOGICA ACTUAL
-- ============================================
SELECT
  *,
  'Medicion LOGICA ACTUAL' AS tipo_de_medicion
FROM (
WITH B3 AS(
SELECT A.* , 
  1-(SAFE_DIVIDE(PRECIO_WM,PRECIO_COMP)) AS PG_LINE
FROM wmt-k1-cons-data-users.k1_adhoc_tables.MEDICION_LOW_A0M1J1N A 
),
SALIDA AS(
SELECT B3.*,CASE WHEN A.FIJACION IS NULL THEN "SIN FIJACION" ELSE A.FIJACION END AS FIJACION,
CASE WHEN A.AC IS NULL THEN "RESTO" ELSE AC END AS AC_DESC,
CASE WHEN A.FLG_AC IS NULL THEN "SIN AC" ELSE FLG_AC END AS FLG_AC,
CASE WHEN PG_LINE<-0.15 THEN "<-15%" ELSE 
CASE WHEN PG_LINE>=-0.15 AND PG_LINE<-0.12 THEN "-15% A -12%" ELSE 
CASE WHEN PG_LINE>=-0.12 AND PG_LINE<-0.09 THEN "-12% A -9%" ELSE 
CASE WHEN PG_LINE>=-0.09 AND PG_LINE<-0.06 THEN "-9% A -6%" ELSE 
CASE WHEN PG_LINE>=-0.06 AND PG_LINE<-0.03 THEN "-6% A -3%" ELSE 
CASE WHEN PG_LINE>=-0.03 AND PG_LINE<0 THEN "-3% A 0%" ELSE 
CASE WHEN PG_LINE>=0 AND PG_LINE<0.03 THEN "0% A 3%" ELSE 
CASE WHEN PG_LINE>=0.03 AND PG_LINE<0.06 THEN "3% A 6%" ELSE 
CASE WHEN PG_LINE>=0.06 AND PG_LINE<0.09 THEN "6% A 9%" ELSE 
CASE WHEN PG_LINE>=0.09 AND PG_LINE<0.12 THEN "9% A 12%" ELSE 
CASE WHEN PG_LINE>=0.12 AND PG_LINE<0.15 THEN "12% A 15%" ELSE 
CASE WHEN PG_LINE>=0.15 THEN ">15%" ELSE "REVISAR" END END END END END END END END END END END END AS RANGOS,
CASE WHEN ITEM_WM IS NULL THEN "NO" ELSE "SI" END AS CANASTA_BASICA,
CASE WHEN CATEGORIA_PERCEPCION IS NULL THEN "NO" ELSE "SI" END AS CATEGORIA_PERCEPCION,
CASE WHEN B.CADENA IS NOT NULL THEN "SI" ELSE "NO" END AS COMPETIDOR_NIELSEN,
FROM b3
LEFT JOIN wmt-k1-cons-data-users.k1_adhoc_tables.PRICING_INFO_CAM_A0M1J1N_AC A 
ON A.ITEM = B3.ITEM AND A.FORMATO = B3.FORMATO AND A.ANIO = B3.ANIO AND A.SW = B3.SW
left join wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0g0dn3_competidores_nielsen B 
ON B3.PAIS = B.PAIS AND b3.COMPETIDOR=B.CADENA 
LEFT JOIN (SELECT DISTINCT ITEM_WM FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_canasta_basica`) CB ON CB.ITEM_WM = B3.ITEM
LEFT JOIN(SELECT distinct categoria_percepcion, pais FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_categorias_percepcion` ) CP ON CP.CATEGORIA_PERCEPCION = B3.CATEGORIA AND CP.PAIS = B3.PAIS
WHERE ID_SW IN (SELECT DISTINCT ID_SW FROM B3 ORDER BY 1 DESC LIMIT 6)
),
SALIDA_2 AS (
SELECT 
DISTINCT 
A.ITEM AS ITEM_NBR, 
FLG_AC AS ACTIVIDAD_COMERCIAL, 
FLG_AC,A.ANIO,
A.CATEGORIA,
A.MP_MC,
VENDOR_NAME,
--SUBDIVISION,
CATEGORIA_PERCEPCION,
COD_CANASTO, 
COMPETIDOR, 
CODIGO_ZONA AS COD_ZONA,
DEPTO AS DEP_NBR, 
ITEM_DESCRIP ASDESCRIPCION,
A.DIVISION,
FIJACION ASFIJACIONES,
KVI_NBB,
MES,
OPPAS FLAG_OPP,
PAIS,
ROL_CANASTO AS ROLL_CANASTO,
A.ID_SW,
A.SW AS SEMANA, 
UPC , 
ZONA,
CANASTA_BASICA AS FLAG_CANASTA_BASICA,
FLAG_CHPR_COMP ASFLAG_COMP_MB, 
PRECIO_COMP AS PRECIO_COMP_PONDERADO , 
PRECIO_WM ASPRECIO_WM_PONDERADO,
PESO AS PESO_CAM,
FACTOR AS FACTOR,
PESO_CALC AS PESO_MB,
FACTOR_CALC AS FACTOR_MB,
MB,
PARTICIPA AS PARTICIPA_MB,
MB_CALC AS MB_MB_CALC,
PARTICIPA_CALC AS PARTICIPA_MB_CALC,
PG_LINE ASPRICE_GAP,
RANGOS ASRANGO_PG,
DIVISION_COMERCIAL,
COMPETIDOR_NIELSEN,
AC_DESC AS TIPO_AC,
FORMATO,
SUBDIVISION,
brand_name as Marca,
COMP_RCCN AS COMPE_REACCION,
CONCAT(FLANKER,"-",CARRITO) AS FLAG_FC,
FACTOR_META_BASE AS FACTOR_META,
PESO_META_BASE AS PESO_META,
CASE WHEN FLAG IS NULL THEN "ELIMINADO" ELSE FLAG END AS FLAG_CANASTO_NUEVO,
CASE WHEN E.CATEGORIA IS NULL THEN "NO" ELSE "SI" END AS ENFOQUE
 FROM SALIDA A
LEFT JOIN(SELECT DISTINCT ITEM_NBR, COMP_NM, zone_cd, CAST(ID AS INT64) AS ID_SW, reaction_comp_nm AS COMP_RCCN, item_subdiv AS SUBDIVISION, YR_NBR,WM_WK_NBR,prcsmrt_bskt_flg AS PS
FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_price_gap
LEFT JOIN `wmt-k1-cons-data-users.k1_adhoc_tables.DIAS_WM_INDEX` AS INDICE 
ON CONCAT(INDICE.ANIO,INDICE.WM_WK) = CONCAT(YR_NBR,WM_WK_NBR)
WHERE role_att IN ("MEDICION")
AND price_type="CORPORATIVO"
and wfm_flg in ("False","NO") 
AND YR_NBR in(2026,2025)) B ON A.ITEM = B.ITEM_NBR AND A.COMPETIDOR=B.COMP_NM AND A.CODIGO_ZONA = B.ZONE_CD AND A.ID_SW=B.ID_SW 
LEFT JOIN (SELECT DISTINCT ITEM_NBR, CARRITO, FLANKER,SW,ANIO FROM wmt-k1-cons-data-users.k1_adhoc_tables.items_fc_hstrc_a0m1j1n) 
FC ON A.ITEM = FC.ITEM_NBR AND A.ANIO = FC.ANIO AND A.SW = FC.SW 
LEFT JOIN(SELECT distinct ITEM,flag FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0g0dn3_canasto_universal_extendido`  ) CU ON CU.ITEM = A.ITEM
LEFT JOIN(SELECT DISTINCT CATEGORIA FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0m1j1n_categorias_enfoque` WHERE ENFOQUE = "SI") E ON E.CATEGORIA = A.CATEGORIA),
PERFORMANCE_BQ AS (WITH
PASO_1 AS (
SELECT
DISTINCT 
T1.COD_ZONA AS cod_zona,
T1.FORMATO,
T1.PAIS,
T1.ITEM_NBR AS cod_item,
SAFE_DIVIDE(FACTOR_MB_TW,PESO_MB_TW) AS PG_TW,
SAFE_DIVIDE(FACTOR_MB_LW,PESO_MB_LW) AS PG_LW,
SAFE_DIVIDE(FACTOR_MB_2LW,PESO_MB_2LW) AS PG_2LW,
SAFE_DIVIDE(FACTOR_MB_3LW,PESO_MB_3LW) AS PG_3LW,
SAFE_DIVIDE(FACTOR_MB_4LW,PESO_MB_4LW) AS PG_4LW,
SAFE_DIVIDE(FACTOR_MB_5LW,PESO_MB_5LW) AS PG_5LW,
SAFE_DIVIDE(FACTOR_META_TW,PESO_META_TW) AS META_TW,
SAFE_DIVIDE(FACTOR_META_LW,PESO_META_LW) AS META_LW,
SAFE_DIVIDE(FACTOR_META_2LW,PESO_META_2LW) AS META_2LW,
SAFE_DIVIDE(FACTOR_META_3LW,PESO_META_3LW) AS META_3LW,
SAFE_DIVIDE(FACTOR_META_4LW,PESO_META_4LW) AS META_4LW,
SAFE_DIVIDE(FACTOR_META_5LW,PESO_META_5LW) AS META_5LW,
FROM  SALIDA_2 T1
LEFT JOIN (
 --- TW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_TW,
SUM(FACTOR_MB) FACTOR_MB_TW,
SUM(FACTOR_META) AS FACTOR_META_TW,
SUM(PESO_META) AS PESO_META_TW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW) FROM SALIDA_2 )
 GROUP BY 1,2) T2 ON T1.ITEM_NBR=T2.ITEM_NBR AND T1.COD_ZONA=T2.COD_ZONA
 LEFT JOIN 
 (
   --- LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_LW,
SUM(FACTOR_MB) FACTOR_MB_LW,
SUM(FACTOR_META) AS FACTOR_META_LW,
SUM(PESO_META) AS PESO_META_LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-1 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T3 ON T1.ITEM_NBR=T3.ITEM_NBR AND T1.COD_ZONA=T3.COD_ZONA
  LEFT JOIN 
 (
     --- 2LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_2LW,
SUM(FACTOR_MB) FACTOR_MB_2LW,
SUM(FACTOR_META) AS FACTOR_META_2LW,
SUM(PESO_META) AS PESO_META_2LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-2 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T4 ON T1.ITEM_NBR=T4.ITEM_NBR AND T1.COD_ZONA=T4.COD_ZONA
  LEFT JOIN 
 (
       --- 3LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_3LW,
SUM(FACTOR_MB) FACTOR_MB_3LW,
SUM(FACTOR_META) AS FACTOR_META_3LW,
SUM(PESO_META) AS PESO_META_3LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-3 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T5 ON T1.ITEM_NBR=T5.ITEM_NBR AND T1.COD_ZONA=T5.COD_ZONA
 LEFT JOIN 
 (
--4- LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_4LW,
SUM(FACTOR_MB) FACTOR_MB_4LW,
SUM(FACTOR_META) AS FACTOR_META_4LW,
SUM(PESO_META) AS PESO_META_4LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-4 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T6 ON T1.ITEM_NBR=T6.ITEM_NBR AND T1.COD_ZONA=T6.COD_ZONA
  LEFT JOIN 
  (
--5 LW --- 
SELECT
COD_ZONA,
ITEM_NBR,
min(PRECIO_COMP_PONDERADO) as PRECIO_COMP_PONDERADO,
SUM(PESO_MB) PESO_MB_5LW,
SUM(FACTOR_MB) FACTOR_MB_5LW,
SUM(FACTOR_META) AS FACTOR_META_5LW,
SUM(PESO_META) AS PESO_META_5LW,
FROM SALIDA_2
WHERE ID_SW=(SELECT MAX(ID_SW)-5 FROM SALIDA_2 )
 GROUP BY 1,2
 ) T7 ON T1.ITEM_NBR=T7.ITEM_NBR AND T1.COD_ZONA=T7.COD_ZONA
 ),
 PASO_2 AS (
 SELECT *, CASE  WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=6  THEN 6
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=5  THEN 5
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=4  THEN 4
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=3  THEN 3
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=2  THEN 2
WHEN IF(PG_TW < 0 ,1,0)+IF(PG_LW < 0 ,1,0)+IF(PG_2LW < 0 ,1,0)+IF(PG_3LW < 0 ,1,0)+IF(PG_4LW < 0 ,1,0)+IF(PG_5LW < 0 ,1,0)=1  THEN 1
ELSE NULL
END SEMANAS_NEG,
CASE  WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=6  THEN 6
 WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=5  THEN 5
 WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=4  THEN 4
WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=3  THEN 3
WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=2  THEN 2
WHEN IF(PG_TW > META_TW*1.05 ,1,0)+IF(PG_LW > META_LW*1.05 ,1,0)+IF(PG_2LW > META_2LW*1.05,1,0)+IF(PG_3LW > META_3LW*1.05,1,0)+IF(PG_4LW > META_4LW*1.05 ,1,0)+IF(PG_5LW > META_5LW*1.05 ,1,0)=1  THEN 1
ELSE NULL
END SEMANAS_SOBREMETA,
CASE
  WHEN (PG_TW < 0 AND PG_LW < 0 AND PG_2LW < 0 AND PG_3LW < 0) THEN "NEG 4 WKS"
      WHEN (PG_TW < 0 AND PG_LW < 0 AND PG_2LW < 0) THEN "NEG 3 WKS"
       WHEN (PG_TW < 0 AND PG_LW < 0 ) THEN "NEG 2 WKS"
        WHEN (PG_TW < 0  ) THEN "NEG 1 WKS"
        WHEN (PG_TW IS NULL AND PG_LW IS NULL ) THEN "ULTIMAS 2 WKS SIN PG"
        WHEN (PG_TW > META_TW*1.05) AND (PG_LW> META_LW*1.05) AND (PG_2LW> META_2LW*1.05) AND (PG_3LW> META_3LW*1.05) THEN "EXCEDIDO 4 WKS"
        WHEN (PG_TW > META_TW*1.05) AND (PG_LW> META_LW*1.05) AND (PG_2LW> META_2LW*1.05)  THEN "EXCEDIDO 3 WKS"
        WHEN (PG_TW > META_TW*1.05) AND (PG_LW> META_LW*1.05)   THEN "EXCEDIDO 2 WKS"
       WHEN (PG_TW > META_TW*1.05)  THEN "EXCEDIDO 1 WKS"
       ELSE NULL
    END PERFORMANCE,
COUNT(*) OVER (PARTITION BY cod_item) AS CONTEO,
SUM(CASE WHEN (PG_TW < 0 AND PG_LW < 0 AND PG_2LW < 0 AND PG_3LW < 0)  THEN 1 ELSE 0 END) OVER(PARTITION BY cod_item) AS CONTEO_NEGATIVO
  FROM PASO_1),
FINAL AS (
SELECT * EXCEPT(FIJACION,DETALLE_FIJACION,FIJACION_2), 
CASE WHEN DETALLE_FIJACION IS NOT NULL AND FIJACION_2 IS NOT NULL THEN CONCAT(DETALLE_FIJACION,"/",FIJACION_2) WHEN DETALLE_FIJACION IS NOT NULL THEN DETALLE_FIJACION ELSE FIJACION_2
 END AS DETALLE_FIJACION
 FROM (
  SELECT A.*,safe_divide(conteo_negativo,conteo) as porc_negativos_zonas,
  case when b.DETALLE_FIJACION like "%MOM%" THEN B.DETALLE_FIJACION WHEN B.DETALLE_FIJACION IS NOT NULL AND C.FIJACION IS NOT NULL THEN CONCAT(DETALLE_FIJACION,"/",C.FIJACION)
  WHEN DETALLE_FIJACION IS NOT NULL AND C.FIJACION IS NULL THEN DETALLE_FIJACION ELSE C.FIJACION END AS DETALLE_FIJACION,
  CASE WHEN D.FIJACION IS NOT NULL AND R.FIJACION IS NOT NULL THEN CONCAT(D.FIJACION,"/",R.FIJACION) WHEN D.FIJACION IS NOT NULL THEN D.FIJACION ELSE R.FIJACION END AS FIJACION_2, 
  R.FIJACION,c.fijacion as fijacion_mom,d.FIJACION as fijacion_max,r.FIJACION as fijacion_comercial
  FROM PASO_2 A
  LEFT jOIN (SELECT ITEM,COD_ZONA,FIJACION AS DETALLE_FIJACION,CASE WHEN FIJACION LIKE "%MD%" OR FIJACION LIKE "%RB%" OR FIJACION LIKE "%GP%" OR FIJACION LIKE "%AT%" OR FIJACION LIKE "%EV_4K%" THEN "Y" ELSE "X" END AS FIJACION
  FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_historico_insumos WHERE EXTRACT_DATE=(SELECT MAX(EXTRACT_DATE) FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_historico_insumos )AND FIJACION IS NOT NULL) B
  ON A.COD_ITEM=B.ITEM AND A.COD_ZONA=B.COD_ZONA
left join (SELECT * FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_fijaciones_estrategia` WHERE FIJACION LIKE"%MOM%") c on a.cod_item=c.item and a.cod_zona=c.cod_zona
  left join (SELECT * FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_fijaciones_estrategia` WHERE FIJACION LIKE"%MAX%") d on a.cod_item=D.item and a.cod_zona=d.cod_zona
  left join (SELECT DISTINCT ITEM_NBR,COD_ZONA,"FIJACION COMERCIAL" AS FIJACION FROM `wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0u01jb_fijacion_comercial`) R on a.cod_item=R.ITEM_NBR and a.cod_zona=R.cod_zona))
  SELECT *, CASE WHEN DETALLE_FIJACION LIKE "%MD%" OR DETALLE_FIJACION LIKE "%RB%" OR DETALLE_FIJACION LIKE "%GP%" OR DETALLE_FIJACION LIKE "%AT%" OR DETALLE_FIJACION LIKE "%EV_4K%" 
  OR DETALLE_FIJACION LIKE "%FIJACION COMERCIAL%"
  THEN "Y" WHEN DETALLE_FIJACION LIKE "%MOM%" OR DETALLE_FIJACION LIKE "%MAX%" THEN "X"  ELSE NULL END AS FIJACION, CASE WHEN DETALLE_FIJACION IS NOT NULL THEN "FIJADO" ELSE "NO FIJADO"
   END AS FLAG_FIJADO,fijacion_mom
   FROM FINAL
)
SELECT A.*,SEMANAS_NEG,SEMANAS_SOBREMETA,PERFORMANCE,CASE WHEN porc_negativos_zonas >=0.9 THEN "90% ZONAS NEG 4WK" WHEN porc_negativos_zonas >=0.5 THEN "50% ZONAS NEG 4WK"  ELSE NULL END AS ZONAS_NEGATIVO,DETALLE_FIJACION,FIJACION,FLAG_FIJADO,SEMANAS_NEGATIVAS_CONSECUTIVAS, SEMANAS_SOBRE_META_CONSECUTIVAS, 
CASE WHEN CLASIFICACION_ACTUAL IS NULL THEN KVI_NBB ELSE CLASIFICACION_ACTUAL END AS CLASIFICACION_ACTUAL,CLASIFICACION_ANTERIOR,FLAG_CANASTO_ANTERIOR,CASE WHEN FLAG_CANASTO_ACTUAL IS NULL THEN "CANASTO ACTUAL" ELSE FLAG_CANASTO_ACTUAL END AS FLAG_CANASTO_ACTUAL, 
CASE WHEN FLAG_CANASTO_ANTERIOR = "CANASTO ANTERIOR" AND FLAG_CANASTO_ACTUAL = "CANASTO ACTUAL" THEN "MANTIENE" WHEN FLAG_CANASTO_ANTERIOR = "CANASTO ANTERIOR" AND FLAG_CANASTO_ACTUAL = "NO CANASTO ACTUAL" THEN "SALE"WHEN FLAG_CANASTO_ANTERIOR = "NO CANASTO ANTERIOR" AND FLAG_CANASTO_ACTUAL = "CANASTO ACTUAL" THEN "ENTRA" ELSE "MANTIENE" END AS DETALLES_CANASTO
FROM SALIDA_2 A 
LEFT JOIN (select cod_item,cod_zona,min(semanas_neg) as semanas_neg,min(SEMANAS_SOBREMETA) as SEMANAS_SOBREMETA, min(PERFORMANCE) as PERFORMANCE, min(porc_negativos_zonas) as porc_negativos_zonas, min(detalle_fijacion) as detalle_fijacion, min(fijacion) as fijacion, min(flag_fijado) as flag_fijado from PERFORMANCE_BQ group by all) B ON A.ITEM_NBR=B.COD_ITEM AND A.COD_ZONA=B.COD_ZONA
LEFT JOIN(SELECT DISTINCT ITEM,CODIGO_ZONA,MAX(SEMANAS_NEGATIVAS_CONSECUTIVAS) SEMANAS_NEGATIVAS_CONSECUTIVAS, MAX(SEMANAS_SOBRE_META_CONSECUTIVAS)SEMANAS_SOBRE_META_CONSECUTIVAS  FROM `wmt-k1-cons-data-users.k1_adhoc_tables.performance_consecutivo`  GROUP BY 1,2) C ON C.ITEM = A.ITEM_NBR AND C.CODIGO_ZONA = A.COD_ZONA  
LEFT JOIN (SELECT ITEM,FORMATO,CLASIFICACION_ACTUAL,CLASIFICACION_ANTERIOR,FLAG_CANASTO_ACTUAL,FLAG_CANASTO_ANTERIOR FROM wmt-k1-cons-data-users.k1_adhoc_tables.prcng_info_cam_a0m1j1n_canasto_tw_vs_lw) D ON D.ITEM = A.ITEM_NBR AND D.FORMATO = A.FORMATO
)