SELECT ITEM, PAIS, COMPETIDOR, FORMATO, ZONA, CODIGO_ZONA, PRECIO_COMP_LOW, PRECIO_WM_LOW, COUNT(*) as n
FROM `wmt-k1-cons-data-users.k1_adhoc_tables.PGMB_PREMED_A0M1J1N`
WHERE ANIO = 2026 AND SW = 8
GROUP BY ITEM, PAIS, COMPETIDOR, FORMATO, ZONA, CODIGO_ZONA, PRECIO_COMP_LOW, PRECIO_WM_LOW
HAVING COUNT(*) > 1
LIMIT 5